import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";
import NextAuthProviders from "./Providers/NextAuthProviders";

export const metadata = {
  title: "Flow Sync Project",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <NextAuthProviders>
        <body className={poppins.className}>
          <div className="min-h-screen">
            {children}
            <ToastContainer position="top-right" />
          </div>
          <div>
            <Footer />
          </div>
        </body>
      </NextAuthProviders>
    </html>
  );
}
